### PR TITLE
Cymetric - finally

### PR DESCRIPTION
**Pull request by scopatz**
This builds a cymetric package on mac and linux and is a companion to cyclus/cymetric#44.  A successful run can be found at http://submit-1.batlab.org/nmi/results/details?groupBy=platform&runID=304888&groupDirection=down&sortDirection=down&sortBy=taskID

### CODE REVIEW

**Comment by gidden** [comment]
do we expect two skips?

**Comment by scopatz** [comment]
Yes, those are from PyNE - which we don't have a sufficiently up-to-date conda package for. Impetus for v0.5, eh?

**Comment by gidden** [comment]
ok, this looks good. great work! =)

**Comment by scopatz** [comment]
Thank you, thank you.

**Comment by opotowsky** [comment]
WOOHOO!!!!

**Pull request merged**
