### PR TITLE
input dir now copied as well

### PR DESCRIPTION
**Pull request by gidden**
should fix new nightly tests

### CODE REVIEW

**Comment by scopatz** [comment]
Do you have a link to a job that shows that this works?

**Comment by gidden** [comment]
We're having massive internet trouble at the sprint, so not yet.

On Thu, Jan 8, 2015 at 1:18 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Do you have a link to a job that shows that this works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/ciclus/pull/52#issuecomment-69232647>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
Sorry to hear that.

**Comment by gidden** [comment]
here's a working example: http://submit-1.batlab.org/nmi/results/details?runID=291611

**Comment by gidden** [comment]
For posterity, from our email exchange: "So I'm at a loss as to why this would have passed the original CI, but now fails in the nightlies. Both call `nosetest -sw cycatest`. This leads me to believe that somehow our CI did not run the same tests. In fact, the CI ran 39 python-based tests, whereas our nightlies ran 13. I would expect a lower number because I could not use yield statements."

**Comment by gidden** [comment]
We should pass CI with this pulled in tonight.

**Comment by scopatz** [comment]
Thanks matt

**Pull request merged**
