### PR TITLE
adding asmeurer channel to condarc

### PR DESCRIPTION
**Pull request by opotowsky**

### CODE REVIEW

**Comment by gidden** [comment]
Can you provide some context, @opotowsky?

On Wed, Feb 18, 2015 at 12:21 PM, opotowsky <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cyclus/ciclus/pull/57
> Commit Summary
>
>    - adding asmeurer channel to condarc
>
> File Changes
>
>    - *M* condarc <https://github.com/cyclus/ciclus/pull/57/files#diff-0>
>    (1)
>
> Patch Links:
>
>    - https://github.com/cyclus/ciclus/pull/57.patch
>    - https://github.com/cyclus/ciclus/pull/57.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/ciclus/pull/57>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by opotowsky** [comment]
Without this channel, conda can't find things like glib or sigcpp. Anthony suggested this should be something that is just part of the condarc file in general.

**Comment by gidden** [comment]
Thanks!

On Wed, Feb 18, 2015 at 12:40 PM, opotowsky <notifications@github.com>
wrote:

> Without this channel, conda can't find things like glib or sigcpp. Anthony
> suggested this should be something that is just part of the condarc file in
> general.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/ciclus/pull/57#issuecomment-74921103>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
We normally request a working CI example to any changes in ciclus. Can you provide one?

**Comment by opotowsky** [comment]
I'm not sure what you mean by that, but I'll take a stab and you can tell me what else to do. 

The initial error:
`opotowsky_eats_CakeBalls ~/cyclus/ciclus (cym) $ conda install glib
Fetching package metadata: ......
Error: No packages found in current linux-64 channels matching: glib

Did you mean one of these?

glibmm, zlib
You can search for this package on Binstar with

binstar search -t conda glib`

Now:
`opotowsky_eats_CakeBalls ~/cyclus/ciclus (rc) $ conda install glib
Fetching package metadata: ........
Solving package specifications: .
# All requested packages already installed.
# packages in environment at /home/opotowsky/miniconda:
#
glib                      2.43.0 `

**Comment by scopatz** [comment]
Hi @opotowsky - @gidden means that you should 

1. log into batlab
2. clone your copy of ciclus into a new copy of the repo (eg I have 'ciclus-scopz' in the home directory)
3. check out this branch (rc)
4. run the command `./submit.sh cycamore.fast.run-spec`
5. This will (after a few seconds) give you a URL to the run. Go this page and wait for run to succeed.
6. Post the link in this issue and say "It works!"
7. ???
8. Profit

**Comment by opotowsky** [comment]
Yall.

It fails already. So I've learned adding one word IS dangerous ;-P

http://submit-1.batlab.org/nmi/results/details?runID=302834

**Comment by gidden** [comment]
Can you try running from your master branch just to confirm?

On Thu, Feb 19, 2015 at 1:42 PM, opotowsky <notifications@github.com> wrote:

> Yall.
>
> It fails already. So I've learned adding one word IS dangerous ;-P
>
> http://submit-1.batlab.org/nmi/results/details?runID=302834
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/ciclus/pull/57#issuecomment-75121380>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by opotowsky** [comment]
On it!

**Comment by opotowsky** [comment]
To Summarize:
master branch passes: http://submit-1.batlab.org/nmi/results/details?runID=302911
this PR fails mac: http://submit-1.batlab.org/nmi/results/details?runID=302834

(has anyone ever submitted a PR with fewer character changes than this?)

**Comment by scopatz** [comment]
I don't think that this failure is due to this PR, per say.  We have some boost funny business going on that this exposes.

**Comment by opotowsky** [comment]
DRAT.

**Pull request closed without merging**
